/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import SistemaClimatizacion.Climatizacion;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Joan
 */
public class PanelClimatizacion extends javax.swing.JPanel {
   private Climatizacion clima;

    /**
     * Creates new form PanelClimatizacion
     */
    public PanelClimatizacion() {
        initComponents();
        clima = new Climatizacion();
        
        sliderTemperatura.setMinimum(16);
        sliderTemperatura.setMaximum(30);
        sliderTemperatura.setValue(clima.getTemperatura());

         lblTemperatura.setText("Temperatura: " + clima.getTemperatura() + "°C");

        // Listener para actualizar etiqueta y modelo Climatizacion
        sliderTemperatura.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int temp = sliderTemperatura.getValue();
                lblTemperatura.setText("Temperatura: " + temp + "°C");
                clima.setTemperatura(temp); // opcional: si querés que afecte el objeto también
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        sliderTemperatura = new javax.swing.JSlider();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        lblVelocidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(51, 0, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Climatizacion");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemperatura.setText("\"Temperatura: 22°C\"");
        add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        sliderTemperatura.setMajorTickSpacing(2);
        sliderTemperatura.setMaximum(30);
        sliderTemperatura.setMinimum(16);
        sliderTemperatura.setPaintLabels(true);
        sliderTemperatura.setPaintTicks(true);
        sliderTemperatura.setSnapToTicks(true);
        sliderTemperatura.setToolTipText("");
        sliderTemperatura.setValue(22);
        add(sliderTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 40));

        btnEncender.setBackground(new java.awt.Color(51, 51, 255));
        btnEncender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEncender.setText("EncenderAC");
        add(btnEncender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, 30));

        btnApagar.setBackground(new java.awt.Color(255, 51, 51));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnApagar.setText("ApagarAC");
        add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, 30));

        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setText("EncenderCalefaccion");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 150, -1));

        jButton4.setText("ApagarCalefaccion");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, -1));

        jSlider1.setMajorTickSpacing(15);
        jSlider1.setMaximum(50);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(25);
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 50));

        lblVelocidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVelocidad.setText("\"VelocidadVentilador\"");
        add(lblVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JSlider sliderTemperatura;
    // End of variables declaration//GEN-END:variables
}
